export const ALERT_MESSAGES = {
  CREATE_SUCCESSFULLY: 'alert form create successfully',
  CREATE_FAILED: 'create failed',
  UPDATE_SUCCESSFULLY: 'alert form update successfully',
  UPDATE_FAILED: 'update failed',
  UNIT_ID_REQUIRED: 'Unit ID is required',
  UNIT_ID_INVALID: 'Unit ID must be a valid MongoDB ObjectId',
  STAFF_CITIZEN_ID_REQUIRED: 'Staff citizen ID is required',
  STAFF_CITIZEN_ID_INVALID: 'Staff citizen ID must be a string',
  MEMBER_CITIZEN_ID_REQUIRED: 'Member citizen ID is required',
  MEMBER_CITIZEN_ID_INVALID: 'Member citizen ID must be a string',
  BLOOD_TYPE_REQUIRED: 'Blood type is required',
  BLOOD_TYPE_INVALID: 'Invalid blood type',
  QUANTITY_REQUIRED: 'Quantity is required',
  QUANTITY_INVALID: 'Quantity must be a positive integer',
  URGENCY_REQUIRED: 'Urgency level is required',
  URGENCY_INVALID: 'Urgency level must be one of STANDARD, MEDIUM, HIGH, CRITICAL',
  APPOINTMENT_DATE_REQUIRED: 'Appointment date is required',
  APPOINTMENT_DATE_INVALID: 'Invalid appointment date format',
  FACILITY_ID_REQUIRED: 'Facility ID is required',
  FACILITY_ID_INVALID: 'Invalid MongoDB ObjectId',
  NOTE_INVALID: 'Note must be a string',
  STATUS_INVALID: 'Invalid status',
  ALERT_NOT_FOUND: 'Alert not found',
  FACILITY_NAME_INVALID: 'Facility name must be a string',
  CONTACT_OWNER_NAME_INVALID: 'Contact owner name must be a string',
  CONTACT_OWNER_PHONE_INVALID: 'Invalid contact owner phone number',
  DELETE_SUCCESSFULLY: 'delete successfully',
  DELETE_FAILED: 'delete failed',
  RESOLVE_SUCCESSFULLY: 'resolve successfully'
}
